trigger:
  branches:
    include: ['*']

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: 'Install Rust'
  - script: git submodule update --init --recursive
    displayName: 'Fetch botocore sources'
  - script: make build
    displayName: 'Generate services and compile everything'
